language: scala
sudo: required
dist: trusty

git:
  depth: false

matrix:
  include:
  - stage: build
    env: CI_SCRIPT=ci/test-mill-release.sh
    jdk: oraclejdk8
  - stage: build
    env: CI_SCRIPT=ci/test-mill-release.sh
    jdk: oraclejdk9

  - stage: build
    env: CI_SCRIPT=ci/test-mill-dev.sh
    jdk: oraclejdk10
  - stage: build
    env: CI_SCRIPT=ci/test-mill-dev.sh
    jdk: oraclejdk11

  - stage: build
    env: CI_SCRIPT=ci/test-mill-bootstrap-0.sh
    jdk: oraclejdk8

  - stage: build
    env: CI_SCRIPT=ci/test-mill-bootstrap-1.sh
    jdk: oraclejdk9

  - stage: build
    env: CI_SCRIPT=ci/test-mill-0.sh
    jdk: oraclejdk10
  - stage: build
    env: CI_SCRIPT=ci/test-mill-1.sh
    jdk: oraclejdk11
  - stage: build
    env: CI_SCRIPT=ci/test-mill-2.sh
    jdk: oraclejdk8


  - stage: release
    env: CI_SCRIPT="ci/on-master.py ci/release.sh"
    jdk: oraclejdk8
  - stage: release
    env: CI_SCRIPT="ci/on-master.py ci/publish-docs.sh"
    jdk: oraclejdk8

script:
  - "$CI_SCRIPT"

cache:
  directories:
  - $HOME/.coursier
